import { NextResponse } from 'next/server'

// Static product data from api/server.js
const products = [
  {
    id: '1',
    title: 'Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops',
    price: 109.95,
    description:
      'Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday',
    category: "men's clothing",
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '2',
    title: 'Mens Casual Premium Slim Fit T-Shirts',
    price: 22.3,
    description:
      'Slim-fitting style, contrast raglan long sleeve, three-button henley placket, light weight & soft fabric for breathable and comfortable wearing.',
    category: "men's clothing",
    image: 'https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '3',
    title: 'Mens Cotton Jacket',
    price: 55.99,
    description:
      'Great outerwear jackets for Spring/Autumn/Winter, suitable for many occasions, such as working, hiking, camping, mountain/rock climbing, cycling, traveling or other outdoors.',
    category: "men's clothing",
    image: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '4',
    title: 'Mens Casual Slim Fit',
    price: 15.99,
    description:
      'The color could be slightly different between on the screen and in practice. Please note that body builds vary by person, therefore, detailed size information should be reviewed below on the product description.',
    category: "men's clothing",
    image: 'https://images.unsplash.com/photo-1586790170083-2f9ceadc732d?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '5',
    title: "John Hardy Women's Legends Naga Gold & Silver Dragon Station Chain Bracelet",
    price: 695,
    description:
      "From our Legends Collection, the Naga was inspired by the mythical water dragon that protects the ocean's pearl. Wear facing inward to be bestowed with love and abundance, or outward for protection.",
    category: 'jewelery',
    image: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '7',
    title: 'White Gold Plated Princess',
    price: 9.99,
    description:
      "Classic Created Wedding Engagement Solitaire Diamond Promise Ring for Her. Gifts to spoil your love more for Engagement, Wedding, Anniversary, Valentine's Day...",
    category: 'jewelery',
    image: 'https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '8',
    title: 'Pierced Owl Rose Gold Plated Stainless Steel Double',
    price: 10.99,
    description: 'Rose Gold Plated Double Flared Tunnel Plug Earrings. Made of 316L Stainless Steel',
    category: 'jewelery',
    image: 'https://images.unsplash.com/photo-1506630448388-4e683c67ddb0?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '9',
    title: 'WD 2TB Elements Portable External Hard Drive - USB 3.0',
    price: 64,
    description:
      "USB 3.0 and USB 2.0 Compatibility Fast data transfers Improve PC Performance High Capacity; Compatibility Formatted NTFS for Windows 10, Windows 8.1, Windows 7; Reformatting may be required for other operating systems; Compatibility may vary depending on user's hardware configuration and operating system",
    category: 'electronics',
    image: 'https://images.unsplash.com/photo-1542393545-10f5cde2c810?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '10',
    title: 'SanDisk SSD PLUS 1TB Internal SSD - SATA III 6 Gb/s',
    price: 109,
    description:
      'Easy upgrade for faster boot up, shutdown, application load and response (As compared to 5400 RPM SATA 2.5 inch hard drive; Based on published specifications and internal benchmarking tests using PCMark vantage scores) Boosts burst write performance, making it ideal for typical PC workloads',
    category: 'electronics',
    image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '11',
    title: 'Silicon Power 256GB SSD 3D NAND A55 SLC Cache Performance Boost SATA III 2.5',
    price: 109,
    description:
      '3D NAND flash are applied to deliver high transfer speeds Remarkable transfer speeds that enable faster bootup and improved overall system performance. The advanced SLC Cache Technology allows performance boost and longer lifespan 7mm slim design suitable for Ultrabooks and Ultra-slim notebooks. Supports TRIM command, Garbage Collection technology, RAID, and ECC (Error Checking & Correction) to provide the optimized performance and enhanced reliability.',
    category: 'electronics',
    image: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '12',
    title: 'WD 4TB Gaming Drive Works with Playstation 4 Portable External Hard Drive',
    price: 114,
    description:
      "Expand your PS4 gaming experience, Play anywhere Fast and easy, setup Sleek design with high capacity, 3-year manufacturer's limited warranty",
    category: 'electronics',
    image: 'https://images.unsplash.com/photo-1498049794561-7780e7231661?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '13',
    title: 'Acer SB220Q bi 21.5 inches Full HD (1920 x 1080) IPS Ultra-Thin',
    price: 599,
    description:
      '21. 5 inches Full HD (1920 x 1080) widescreen IPS display And Radeon free Sync technology. No compatibility for VESA Mount Graphic Type: Integrated; Backlight: LED; Frame Rate: 75 Hz; Refresh Rate: 75 Hz. Ports: 1 x HDMI & 1 x VGA',
    category: 'electronics',
    image: 'https://images.unsplash.com/photo-1542393545-10f5cde2c810?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '14',
    title: 'Samsung 49-Inch CHG90 144Hz Curved Gaming Monitor (LC49HG90DMNXZA) – Super Ultrawide Screen QLED',
    price: 999.99,
    description:
      '49 INCH SUPER ULTRAWIDE 32:9 CURVED GAMING MONITOR with dual 27 inch screen side by side QUANTUM DOT (QLED) TECHNOLOGY, HDR support and factory calibration provides stunningly realistic and accurate color and contrast 144HZ HIGH REFRESH RATE and 1ms ultra fast response time work to eliminate motion blur, ghosting, and reduce input lag',
    category: 'electronics',
    image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '15',
    title: "BIYLACLESEN Women's 3-in-1 Snowboard Jacket Winter Coats",
    price: 56.99,
    description:
      'Note:The Jackets is US standard size, Please choose size as your usual wear Material: 100% Polyester; Detachable Liner Fabric: Warm Fleece. Detachable Functional Liner: Skin Friendly, Lightweigt and Warm.Stand Collar Liner jacket, keep you warm in cold weather. Zippered Pockets: 2 Zippered Hand Pockets, 2 Zippered Pockets on Chest (enough to keep cards or keys)and 1 Hidden Pocket Inside.Zippered Hand Pockets and Hidden Pocket keep your things secure. Humanized Design: Adjustable and Detachable Hood and Adjustable cuff to prevent the wind and water,for a comfortable fit. 3 in 1 Detachable Design provide more convenience, you can separate the coat and inner as needed, or wear it together. It is suitable for different season and help you adapt to different climates',
    category: "women's clothing",
    image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '16',
    title: "Lock and Love Women's Removable Hooded Faux Leather Moto Biker Jacket",
    price: 29.95,
    description:
      '100% POLYURETHANE(shell) 100% POLYESTER(lining) 75% POLYESTER 25% COTTON (SWEATER), Faux leather material for style and comfort / 2 pockets of front, 2-For-One Hooded denim style faux leather jacket, Button detail on waist / Detail stitching at sides, HAND WASH ONLY / DO NOT BLEACH / LINE DRY / DO NOT IRON',
    category: "women's clothing",
    image: 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '17',
    title: 'Rain Jacket Women Windbreaker Striped Climbing Raincoats',
    price: 39.99,
    description:
      "Lightweight perfet for trip or casual wear---Long sleeve with hooded, adjustable drawstring waist design. Button and zipper front closure raincoat, fully stripes Lined and The Raincoat has 2 side pockets are a good size to hold all kinds of things, it covers the hips, and the hood is generous but doesn't overdo it.Attached Cotton Lined Hood with Adjustable Drawstrings give it a real styled look.",
    category: "women's clothing",
    image: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '18',
    title: "MBJ Women's Solid Short Sleeve Boat Neck V",
    price: 9.85,
    description:
      '95% RAYON 5% SPANDEX, Made in USA or Imported, Do Not Bleach, Lightweight fabric with great stretch for comfort, Ribbed on sleeves and neckline / Double stitching on bottom hem',
    category: "women's clothing",
    image: 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '19',
    title: "Opna Women's Short Sleeve Moisture",
    price: 7.95,
    description:
      '100% Polyester, Machine wash, hang dry, v-neck, moisture-wicking, MADE IN USA, lightweight, roomy and highly breathable with moisture wicking fabric which helps to keep moisture away from the skin',
    category: "women's clothing",
    image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '20',
    title: 'DANVOUY Womens T Shirt Casual Cotton Short',
    price: 12.99,
    description:
      '95%Cotton,5%Spandex, Features: Casual, Short Sleeve, Letter Print,V-Neck,Fashion Tees, The fabric is soft and has some stretch., Occasion: Casual/Office/Beach/School/Home/Street. Season: Spring,Summer,Autumn,Winter.',
    category: "women's clothing",
    image: 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '21',
    title: 'Apple iPhone 15 Pro Max',
    price: 1199.99,
    description: 'Latest iPhone with titanium design, A17 Pro chip, and pro camera system with 5x telephoto zoom.',
    category: 'electronics',
    image: 'https://images.unsplash.com/photo-1605787020600-b9ebd5df1d07?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '22',
    title: 'Nike Air Max 270 Running Shoes',
    price: 149.99,
    description: 'Lightweight running shoes with Max Air unit in the heel for maximum comfort and style.',
    category: "men's clothing",
    image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '23',
    title: "Adidas Women's Ultraboost 22",
    price: 189.99,
    description: 'Energy-returning running shoes with responsive Boost midsole and Primeknit upper.',
    category: "women's clothing",
    image: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '24',
    title: 'Sony WH-1000XM5 Wireless Headphones',
    price: 399.99,
    description: 'Industry-leading noise canceling with exceptional sound quality and 30-hour battery life.',
    category: 'electronics',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '25',
    title: "Levi's 501 Original Fit Jeans",
    price: 89.99,
    description: 'Classic straight leg jeans with authentic details and premium denim construction.',
    category: "men's clothing",
    image: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '26',
    title: 'Tiffany & Co. Return to Tiffany Heart Necklace',
    price: 325,
    description: 'Sterling silver heart tag pendant necklace with iconic Tiffany Blue enamel finish.',
    category: 'jewelery',
    image: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '27',
    title: 'MacBook Air M2 13-inch',
    price: 1099.99,
    description: 'Supercharged by M2 chip with 8-core CPU and 8-core GPU, featuring all-day battery life.',
    category: 'electronics',
    image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '28',
    title: "Zara Women's Blazer",
    price: 79.99,
    description: 'Tailored blazer with lapel collar and long sleeves. Front button fastening.',
    category: "women's clothing",
    image: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '29',
    title: 'Canon EOS R5 Mirrorless Camera',
    price: 3899.99,
    description: 'Full-frame mirrorless camera with 45MP resolution and 8K video recording capability.',
    category: 'electronics',
    image: 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '31',
    title: "H&M Men's Cotton T-Shirt",
    price: 12.99,
    description: 'Regular fit cotton t-shirt with crew neck and short sleeves.',
    category: "men's clothing",
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '32',
    title: 'Samsung 55" 4K QLED TV',
    price: 899.99,
    description: 'Quantum dot technology with 4K UHD resolution and smart TV features.',
    category: 'electronics',
    image: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '33',
    title: 'Pandora Charm Bracelet',
    price: 89.99,
    description: 'Sterling silver snake chain bracelet with barrel clasp.',
    category: 'jewelery',
    image: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '34',
    title: "Uniqlo Women's Down Jacket",
    price: 69.99,
    description: 'Ultra light down jacket with water-repellent outer fabric.',
    category: "women's clothing",
    image: 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '35',
    title: 'PlayStation 5 Console',
    price: 499.99,
    description: 'Next-gen gaming console with 4K gaming and ultra-high speed SSD.',
    category: 'electronics',
    image: 'https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '36',
    title: "Nike Men's Dri-FIT Shorts",
    price: 34.99,
    description: 'Athletic shorts with moisture-wicking fabric and comfortable fit.',
    category: "men's clothing",
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '37',
    title: 'Apple Watch Series 9',
    price: 399.99,
    description: 'Advanced smartwatch with health monitoring and GPS tracking.',
    category: 'electronics',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '38',
    title: 'Diamond Stud Earrings',
    price: 599.99,
    description: '0.5 carat total weight diamond stud earrings in 14k white gold.',
    category: 'jewelery',
    image: 'https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '39',
    title: "Mango Women's Midi Dress",
    price: 59.99,
    description: 'Elegant midi dress with floral print and three-quarter sleeves.',
    category: "women's clothing",
    image: 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '40',
    title: 'Bose SoundLink Flex Speaker',
    price: 149.99,
    description: 'Portable Bluetooth speaker with waterproof design and 12-hour battery.',
    category: 'electronics',
    image: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '41',
    title: "Tommy Hilfiger Men's Polo Shirt",
    price: 49.99,
    description: 'Classic fit polo shirt with embroidered logo and short sleeves.',
    category: "men's clothing",
    image: 'https://images.unsplash.com/photo-1586790170083-2f9ceadc732d?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '42',
    title: 'iPad Pro 11-inch',
    price: 799.99,
    description: 'Powerful tablet with M2 chip and Liquid Retina display.',
    category: 'electronics',
    image: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '43',
    title: 'Cartier Love Bracelet',
    price: 6750,
    description: '18k yellow gold bracelet with screw motif and matching screwdriver.',
    category: 'jewelery',
    image: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '44',
    title: "Zara Men's Suit Jacket",
    price: 129.99,
    description: 'Slim fit suit jacket with notched lapels and two-button fastening.',
    category: "men's clothing",
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '45',
    title: 'AirPods Pro 2nd Generation',
    price: 249.99,
    description: 'Active noise cancellation earbuds with spatial audio and MagSafe charging.',
    category: 'electronics',
    image: 'https://images.unsplash.com/photo-1588423771073-b8903fbb85b5?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '46',
    title: "Mango Women's Leather Handbag",
    price: 89.99,
    description: 'Genuine leather handbag with gold-tone hardware and adjustable strap.',
    category: "women's clothing",
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '47',
    title: 'Nintendo Switch OLED',
    price: 349.99,
    description: 'Handheld gaming console with vibrant OLED screen and enhanced audio.',
    category: 'electronics',
    image: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '49',
    title: "Adidas Men's Tracksuit",
    price: 79.99,
    description: 'Comfortable tracksuit with three-stripe design and zip-up jacket.',
    category: "men's clothing",
    image: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '50',
    title: "Calvin Klein Women's Perfume",
    price: 64.99,
    description: 'Elegant floral fragrance with notes of jasmine, rose, and sandalwood.',
    category: "women's clothing",
    image: 'https://images.unsplash.com/photo-1541643600914-78b084683601?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '51',
    title: 'Nike Air Max Sneakers',
    price: 129.99,
    description: 'Comfortable running shoes with air cushioning technology.',
    category: 'spor',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '52',
    title: 'Adidas Football',
    price: 39.99,
    description: 'Professional quality football for training and matches.',
    category: 'spor',
    image: 'https://images.unsplash.com/photo-1575361204480-aadea25e6e68?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '53',
    title: 'Fitness Yoga Mat',
    price: 24.99,
    description: 'Non-slip yoga mat for exercise and meditation.',
    category: 'spor',
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '54',
    title: "L'Oreal Face Cream",
    price: 18.99,
    description: 'Anti-aging face cream with vitamin C and retinol.',
    category: 'kozmetik',
    image: 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '55',
    title: 'MAC Lipstick',
    price: 32.99,
    description: 'Long-lasting matte lipstick in cherry red color.',
    category: 'kozmetik',
    image: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '56',
    title: 'Maybelline Mascara',
    price: 12.99,
    description: 'Waterproof mascara for volume and length.',
    category: 'kozmetik',
    image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '57',
    title: 'Baby Food Organic',
    price: 4.99,
    description: 'Organic baby food puree with fruits and vegetables.',
    category: 'anne-bebek',
    image: 'https://images.unsplash.com/photo-1555252333-9f8e92e65df9?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '58',
    title: 'Baby Stroller',
    price: 249.99,
    description: 'Lightweight baby stroller with safety harness.',
    category: 'anne-bebek',
    image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '59',
    title: 'Baby Diapers Pack',
    price: 29.99,
    description: 'Ultra-soft disposable diapers pack of 50.',
    category: 'anne-bebek',
    image: 'https://images.unsplash.com/photo-1584464491033-06628f3a6b7b?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '61',
    title: 'LEGO Building Set',
    price: 79.99,
    description: 'Creative building blocks set with 500 pieces.',
    category: 'oyuncak',
    image: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '62',
    title: 'Teddy Bear Plush',
    price: 19.99,
    description: 'Soft and cuddly teddy bear for kids.',
    category: 'oyuncak',
    image: 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '63',
    title: 'Cat Food Premium',
    price: 24.99,
    description: 'High-quality dry cat food with salmon flavor.',
    category: 'pet-shop',
    image: 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '64',
    title: 'Dog Collar Leather',
    price: 18.99,
    description: 'Genuine leather dog collar with metal buckle.',
    category: 'pet-shop',
    image: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '65',
    title: 'Bird Cage Large',
    price: 89.99,
    description: 'Spacious bird cage with feeding bowls and perches.',
    category: 'pet-shop',
    image: 'https://images.unsplash.com/photo-1444212477490-ca407925329e?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '67',
    title: 'Acoustic Guitar',
    price: 199.99,
    description: '6-string acoustic guitar perfect for beginners.',
    category: 'film-muzik',
    image: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '68',
    title: 'Bluetooth Headphones',
    price: 79.99,
    description: 'Wireless headphones with noise cancellation.',
    category: 'film-muzik',
    image: 'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '69',
    title: 'Coffee Beans Premium',
    price: 14.99,
    description: 'Arabica coffee beans from Colombian highlands.',
    category: 'supermarket',
    image: 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '70',
    title: 'Olive Oil Extra Virgin',
    price: 22.99,
    description: 'Cold-pressed extra virgin olive oil from Italy.',
    category: 'supermarket',
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '71',
    title: 'Organic Honey',
    price: 16.99,
    description: 'Pure organic honey from wildflower meadows.',
    category: 'supermarket',
    image: 'https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '72',
    title: 'Design Coffee Table Book',
    price: 39.99,
    description: 'Beautiful photography book featuring modern architecture.',
    category: 'kitap',
    image: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '73',
    title: 'JavaScript Programming Guide',
    price: 29.99,
    description: 'Complete guide to modern JavaScript development.',
    category: 'kitap',
    image: 'https://images.unsplash.com/photo-1532012197267-da84d127e765?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '74',
    title: 'Fiction Novel Bestseller',
    price: 17.99,
    description: 'Award-winning contemporary fiction novel.',
    category: 'kitap',
    image: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '75',
    title: 'Tennis Racket Professional',
    price: 149.99,
    description: 'Professional tennis racket with carbon fiber frame.',
    category: 'spor',
    image: 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '76',
    title: 'Sunscreen SPF 50',
    price: 16.99,
    description: 'Water-resistant sunscreen with broad spectrum protection.',
    category: 'kozmetik',
    image: 'https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '77',
    title: 'Baby Monitor Digital',
    price: 89.99,
    description: 'Digital baby monitor with night vision and two-way audio.',
    category: 'anne-bebek',
    image: 'https://images.unsplash.com/photo-1586227740560-8cf2732c1531?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '78',
    title: 'Action Figures Set',
    price: 34.99,
    description: 'Superhero action figures collection with accessories.',
    category: 'oyuncak',
    image: 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400&h=400&fit=crop&crop=center',
  },
  {
    id: '80',
    title: 'Vinyl Records Classic',
    price: 59.99,
    description: 'Classic rock vinyl records collection from the 70s.',
    category: 'film-muzik',
    image: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&h=400&fit=crop&crop=center',
  },
]

export async function GET() {
  return NextResponse.json(products)
}
